<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RaviKiran" name="Test" tests="1" failures="1" timestamp="25 Nov 2015 10:31:42 GMT" time="0.484" errors="0">
  <testcase name="writeExcel" time="0.375" classname="com.excel.ExcelTest">
    <failure type="java.io.FileNotFoundException" message="C:\Users\RaviKiran\Documents\Selenium2\Project2\input_files\NamesXLSFile.xls (The process cannot access the file because it is being used by another process)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\RaviKiran\Documents\Selenium2\Project2\input_files\NamesXLSFile.xls (The process cannot access the file because it is being used by another process)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.excel.ExcelTest.writeExcel(ExcelTest.java:96)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- writeExcel -->
</testsuite> <!-- Test -->
